### ISSUE TITLE
[feature] Аутентификация и авторизация пользователей

### ISSUE THREAD

**Issue by arsenmuk** [cavoke-project/cavoke#101]
- [x] настройка OAuth на Auth0
- [x] `AuthFilter` на сервере
- [x] Обновить схему sql для User `uuid` -> `varchar`
- [x] Обновить API
- [x] #144

**Comment by waleko** [comment]
mock сделан в 3583f826f6d3ae84e1c30fff0c02505849a2f855

**Comment by waleko** [comment]
- используется Oauth через Auth0
- авторизация через браузер на клиенте, после этого Bearer token передаётся с нужными запросами относительно просто и (вроде) сам обновляется через refresh token в фоне
- проверка jwt токена на сервере через фильтр (т.е. можно подключить к любому методу, добавив всего один параметр в контроллере) + user_id передаётся запросам дальше в качестве query, поэтому даже почти ничего менять не придётся в самих контроллерах

**Comment by waleko** [comment]
[branch](https://github.com/cavoke-project/cavoke/tree/feature/auth)

**Comment by waleko** [comment]
Из-за проблем с клиентом, выполено разрезание задач на серверную и клиентскую часть.

PR по серверной части готов #143 к review

С клиентской частью основные проблемы по части `network_manager`.
