### ISSUE TITLE
Docker server image build failed

### ISSUE THREAD

**Issue by MarkTheHopeful** [cavoke-project/cavoke#107]
https://github.com/cavoke-project/cavoke/runs/5883589264?check_suite_focus=true

```
#9 3.547 In file included from /install/cavoke/controllers/sessions_controller.h:7,
#9 3.547                  from /install/cavoke/main.cpp:4:
#9 3.547 /install/cavoke/./model/logic/game_logic_manager.h:6:10: fatal error: ../../../games/cavoke.h: No such file or directory
#9 3.547     6 | #include "../../../games/cavoke.h"
#9 3.547       |          ^~~~~~~~~~~~~~~~~~~~~~~~~
#9 3.547 compilation terminated.
```

**Comment by waleko** [comment]
Проблема в том, что в docker копируется только папка `server`, что логично -- не копируем клиент.

Уже писал про это, хотелось бы cavoke.h куда-нибудь вынести. может в отдельный подмодуль? может просто закинуть в root?

@petrtsv виднее

**Comment by petrtsv** [comment]
Тогда, наверное, вынесу в отдельный модуль
