### ISSUE TITLE
[feature] Load config from file (ex. json)

### ISSUE THREAD

**Issue by petrtsv** [cavoke-project/cavoke#11]
Путь выглядит как минимум странно, возможно, было бы неплохо вынести его куда-нибудь, опять же, возможно, в конфиг

_Originally posted by @MarkTheHopeful in https://github.com/cavoke-project/cavoke/pull/5#discussion_r805393569_

**Comment by waleko** [comment]
https://github.com/cavoke-project/cavoke/tree/feature/server-improvements
