### ISSUE TITLE
Запоминание хоста на сервере

### ISSUE THREAD

**Issue by waleko** [cavoke-project/cavoke#132]
Интересный порядок действий, приводящий к интересному результату:

1. Алиса создаёт игру (хост)
2. Боб присоединяется к игре
3. Алиса выходит из игры
4. Алиса заходит в игру

У меня при переподключении хоста нет кнопок управления игрой. Сессия засофтлочена
![Скриншот 2022-04-28 03 13 01](https://user-images.githubusercontent.com/24986722/165651211-b2b596e0-43cc-4357-ac99-e5596992f3ab.png)

А у нас на сервере хоть где-то хранится, кто хост сессии?.......  @petrtsv Кажется, нет.......

Вроде несложная задача:
- добавить сессии поле `host` foreign key `user`.
- добавить при `start` проверку совпадения `user_id`
- добавить поле хост в `SessionInfo` в API.

@MarkTheHopeful напиши, хочешь сам сделать или отдать кому-то. в целом ты хотел немного попробовать сервер.

_Originally posted by @waleko in https://github.com/cavoke-project/cavoke/pull/131#discussion_r860339917_

**Comment by MarkTheHopeful** [comment]
- [ ] Добавить поле host в таблицу и в SessionInfo
- [ ] При отключении хоста назначать хостом следующего игрока
- [ ] Если игроков не осталось, то удалить сессию или забить

**Comment by MarkTheHopeful** [comment]
done in that PR
