### ISSUE TITLE
[feature] Add a way to connect from the client to the server

### ISSUE THREAD

**Issue by MarkTheHopeful** [cavoke-project/cavoke#14]
Скажем, на экране "создать игру" добавить кнопку "показать список возможных игр", которые спросить у сервера. Обработать ситуацию, когда ~никто не пришёл на фан встречу~ сервер не отвечает

**Comment by waleko** [comment]
есть авто-обновляющийся mock https://github.com/cavoke-project/cavoke/pull/6#issuecomment-1038459577

**Comment by MarkTheHopeful** [comment]
Почти всё готово, но пока нет обработки ошибок, вынесу в отдельное issue
