### ISSUE TITLE
Auth & Display name на клиенте

### ISSUE THREAD

**Issue by waleko** [cavoke-project/cavoke#144]
- [x] OAuth авторизация в браузере на клиенте
- [x] Секьюрное сохранение refresh токена на клиенте. Нужна библиотека (https://github.com/frankosterfeld/qtkeychain например?)
- [x] interceptor в network manager

**Comment by waleko** [comment]
[branch](https://github.com/cavoke-project/cavoke/tree/feature/client-auth)

**Comment by Girgina** [comment]
> ``

**Comment by Girgina** [comment]
@MarkTheHopeful
