### ISSUE TITLE
[feature] Add some config file for client

### ISSUE THREAD

**Issue by MarkTheHopeful** [cavoke-project/cavoke#15]

**Comment by waleko** [comment]
конфиг чего?

**Comment by MarkTheHopeful** [comment]
Конфиг клиента. Ну, например, уже сейчас нужно где-то хранить адрес, по которому подключаться к серверу.

**Comment by waleko** [comment]
Посмотри https://doc.qt.io/qt-5/qsettings.html

**Comment by MarkTheHopeful** [comment]
Дупликат #95
