### ISSUE TITLE
API with game protocol

### ISSUE THREAD

**Issue by waleko** [cavoke-project/cavoke#21]
Запрототипировал версию API с протоколом во время игры. Смотри https://cavoke.docs.apiary.io/ (postman не понравился).

## Основные нововведения:
- **/sessions/create** — создать сессию (пока что то же самое, что комната — в комнате будем наверное пока играть одну игру один раз)
- **/play/send_move**
- **/play/get_update**

Сущности:
- UserId
- GameId
- SessionId
- GameMove
- GameUpdate

подробные описания в документации

жду фидбека и предложений

**Comment by MarkTheHopeful** [comment]
Кажется, есть некоторая путаница с тем, что является игрой, что является сессией, что является комнатой. Я, вроде как, разобрался, но, думаю, куда-нибудь нужны пояснения. `Create a game from requested game` -- несколько путает, и указывает, что игра как "Сама глобально игра, TicTacToe/Codenames/etc" и игра как "Партия игры во что-то" несколько путаются.

Помимо этого, кажется, нужны ещё запросы на:

- Подключиться к комнате
- Отключиться от комнаты
- Начать партию
- Получить текущий список участников (возможно он будет в `get_update`, конечно, но хотелось бы разграничивать это, и отдавать на `get_update` и `send_move` только и только `QML`-штуки)
- пока вроде всё...

Так же хотелось бы каких-нибудь описаний сущностей `session`, `игрок`, `игра`

**Comment by MarkTheHopeful** [comment]
О, и ещё, кстати, он какие-нибудь mock-и сам делает?

**Comment by waleko** [comment]
> О, и ещё, кстати, он какие-нибудь mock-и сам делает?

Про mock: да, там нажать на какой-нибудь запрос и там будет ссылка на mock и можно сразу `Try console`
![image](https://user-images.githubusercontent.com/24986722/154814235-f5a8ade6-a305-4c6a-bc3d-b66fa32c333d.png)

**Comment by petrtsv** [comment]
Насчет комнаты - согласен, пока что делаем комната = сессия = одна партия в одну игру. Еще нужно, наверное, добавить объект SessionInfo, там поля типа max кол-во игроков, текущее кол-во игроков, коротий код (напр 6 цифр) для подключения. + метод для подключения игрока к сессии

**Comment by waleko** [comment]
@petrtsv @MarkTheHopeful

Немного обновил https://cavoke.docs.apiary.io/

* Добавил `/sessions/join` по `invite_code` из 6 цифр. Потом это наверняка переедет в `room`, так как подключение к комнате, но пока сессия = 1 игра в 1 комнате будет так.
* Добавил `SessionInfo` с `game_id`, `invite_code` и `session_id`. Вот насчёт количества игроков, надо ещё подумать, мне не совсем понятно, как это всё будет работать, и что нужно. Вероятно, первую неделю у нас будут singleplayer крестики-нолики. Возможно, пока не стоит заморачиваться?
* Пофиксил `body` у `send_move`
* Чуть поуточнял описания

**Comment by waleko** [comment]
кажется, все довольны, осталось подключить к github
