### ISSUE TITLE
[feature] Add some more server documentation

### ISSUE THREAD

**Issue by MarkTheHopeful** [cavoke-project/cavoke#34]
Например, в каком формате передавать ходы, какого типа должны быть запросы, какие из описанных в Apiary уже работают и т.д....

**Comment by waleko** [comment]
да, вот ещё есть интересный момент, что пока что оно работает не совсем так, как предложено в apiary.

- [/play/{session_id}/send_move](https://cavoke.docs.apiary.io/#/reference/0/resource-8). В apiary принимает json объект с полем move (потому что потом ещё что-нибудь захочется вместе с ходом передавать), в сервере пока просто text/plain
- [/play/{session_id}/get_update](https://cavoke.docs.apiary.io/#/reference/0/resource-9). В apiary отдаёт объект с оффсетами т.д., чтобы получать много. В сервере пока тоже text/plain последнего

[apiary](https://cavoke.docs.apiary.io)

**Comment by waleko** [comment]
пока закрываю
