### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by waleko** [cavoke-project/cavoke#36]
Кажется, иногда бывает не совсем понятно, что уже сделано, а что нет. Возможно, стоит завести `Changelog.md` для записи изменений?

@petrtsv @MarkTheHopeful

**Comment by MarkTheHopeful** [comment]
Боюсь, только в новом квартале. Сейчас изменения происходят слишком быстро и не всегда согласованно с issues. Вообще, возможно, в новом квартале будет неплохо чуть конкретнее связать всё с user stories, issues и т.д., но, думаю, мы всё это ещё много раз обсудим на пост-пред-защитных собраниях.
