### ISSUE TITLE
Code analysis 

### ISSUE THREAD

**Issue by waleko** [cavoke-project/cavoke#37]
Хочется проверять качество кода.

Из вариантов:

- clang-tidy
- cppcheck
- [LGTM](https://lgtm.com)

Можно какую-то часть из этого, можно всё.

С одной стороны код ещё сыроват и намеренно убогий, с другой стороны его уже достаточно много, и может стоит уже начинать писать нормально, не знаю.

@MarkTheHopeful @petrtsv

**Comment by MarkTheHopeful** [comment]
Кажется, нужно уже отдельно вводить label `Postponed to the next quarter`...

**Comment by waleko** [comment]
resolved by #82 for now: cppcheck + clangformat
