### ISSUE TITLE
При попытке повторно присоединиться к комнате с тем же `user_id` ответ сервера -- 400 без каких-либо комментариев.

### ISSUE THREAD

**Issue by waleko** [cavoke-project/cavoke#63]
При попытке повторно присоединиться к комнате с тем же `user_id` ответ сервера -- 400 без каких-либо комментариев.

UPD: на самом деле нет, похоже, вполне можно несколько раз подключиться к игре, в которой ты уже есть, но при этом ты своими копиями всё же занимаешь слоты

_Originally posted by @MarkTheHopeful in https://github.com/cavoke-project/cavoke/issues/54#issuecomment-1053529654_

**Comment by waleko** [comment]
@MarkTheHopeful не смог воссоздать. у меня пишет, что `player already in session`

**Comment by waleko** [comment]
может лучше вместо ошибки успешно отдавать тот же `session_info`?

**Comment by MarkTheHopeful** [comment]
```
> http POST '127.0.0.1:8080/sessions/create?user_id=1&game_id=1'
HTTP/1.1 200 OK
content-length: 86
content-type: application/json; charset=utf-8
date: Sun, 27 Feb 2022 15:29:56 GMT
server: drogon/1.7.4

{
    "game_id": "1",
    "invite_code": "456166",
    "session_id": "9E3B3D6666724FE7A9AAD77B13E7A6EC"
}


> http POST '127.0.0.1:8080/sessions/join?user_id=1&invite_code=456166'
HTTP/1.1 200 OK
content-length: 86
content-type: application/json; charset=utf-8
date: Sun, 27 Feb 2022 15:30:16 GMT
server: drogon/1.7.4

{
    "game_id": "1",
    "invite_code": "456166",
    "session_id": "9E3B3D6666724FE7A9AAD77B13E7A6EC"
}


> http POST '127.0.0.1:8080/sessions/join?user_id=1&invite_code=456166'
HTTP/1.1 400 Bad Request
content-length: 0
content-type: text/html; charset=utf-8
date: Sun, 27 Feb 2022 15:30:22 GMT
server: drogon/1.7.4



> http GET 127.0.0.1:8080/games/1/get_config
HTTP/1.1 200 OK
content-length: 98
content-type: application/json; charset=utf-8
date: Sun, 27 Feb 2022 15:31:00 GMT
server: drogon/1.7.4

{
    "description": "smart description",
    "display_name": "another dummy_name",
    "id": "1",
    "players_num": 999
}
```

**Comment by MarkTheHopeful** [comment]
```
> http POST '127.0.0.1:8080/sessions/join?user_id=2&invite_code=456166'
HTTP/1.1 200 OK
content-length: 86
content-type: application/json; charset=utf-8
date: Sun, 27 Feb 2022 15:33:18 GMT
server: drogon/1.7.4

{
    "game_id": "1",
    "invite_code": "456166",
    "session_id": "9E3B3D6666724FE7A9AAD77B13E7A6EC"
}


> http POST '127.0.0.1:8080/sessions/join?user_id=2&invite_code=456166'
HTTP/1.1 400 Bad Request
content-length: 0
content-type: text/html; charset=utf-8
date: Sun, 27 Feb 2022 15:33:20 GMT
server: drogon/1.7.4
```

**Comment by waleko** [comment]
кажется, он просто сообщает тебе, что ты уже в сессии. вроде это expected behavior, хоть и убогенько

**Comment by MarkTheHopeful** [comment]
Так вроде это ровно то, что и указывалось в заголовке `issue`...

**Comment by waleko** [comment]
> UPD: на самом деле нет, похоже, вполне можно несколько раз подключиться к игре, в которой ты уже есть, но при этом ты своими копиями всё же занимаешь слоты

я к этому спросил, а в заголовке вроде всё верно

**Comment by waleko** [comment]
яуже почти доделал вывод строки с ошибкой, скоро запушу

**Comment by waleko** [comment]
видимо вопросы: ьесли подключился заново, может лучше вернуть `session_info` ещё раз?

мне кажется так будет удачнее?

**Comment by MarkTheHopeful** [comment]
> > UPD: на самом деле нет, похоже, вполне можно несколько раз подключиться к игре, в которой ты уже есть, но при этом ты своими копиями всё же занимаешь слоты
> 
> я к этому спросил, а в заголовке вроде всё верно

а, ну, тот момент, видимо, был мною не совсем правильно воспринят, я сейчас попробовал воспроизвести -- не получилось
